// Generated by CoffeeScript 1.4.0
(function() {
  var Schema, mongoose, staff, user,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  staff = ['lenincasco', 'sacrac1', 'Belkymf', 'samuelb1311', 'YutaruHD', 'felixricarb', 'Geimsz', 'hosmelQ'];

  user = new Schema({
    username: String,
    location: String,
    provider: String,
    staff: Boolean,
    twitter: {
      id: Number,
      token: String,
      token_secret: String
    },
    facebook: {
      id: Number,
      token_secret: String
    },
    created_at: {
      type: Date,
      "default": Date.now
    },
    banned: Boolean
  });

  user.statics.serialize = function(user, next) {
    return next(null, user._id);
  };

  user.statics.deserialize = function(id, next) {
    return this.findOne({
      _id: id
    }, function(err, user) {
      if (err || user === null) {
        return next(null, false);
      }
      return next(null, user);
    });
  };

  user.statics.twitter = function(token, tokenSecret, profile, next) {
    var model;
    model = this;
    return model.findOne({
      'twitter.id': profile.id
    }, function(err, doc) {
      var u, _ref, _ref1;
      if (err) {
        return next(err);
      }
      if (doc) {
        if (doc.banned) {
          next(null, false);
        }
        doc.username = profile.username;
        doc.location = profile._json.location;
        doc.staff = (_ref = profile.username, __indexOf.call(staff, _ref) >= 0) ? true : false;
        return doc.save(function(err) {
          if (err) {
            throw err;
          }
          return next(null, doc);
        });
      } else {
        u = new (mongoose.model('user'));
        u.twitter.id = profile.id;
        u.twitter.token = token;
        u.twitter.token_secret = tokenSecret;
        u.username = u.username = profile.username;
        u.location = profile._json.location;
        u.provider = profile.provider;
        u.staff = (_ref1 = profile.username, __indexOf.call(staff, _ref1) >= 0) ? true : false;
        return u.save(function(err) {
          if (err) {
            throw err;
          }
          return next(null, u);
        });
      }
    });
  };

  user.statics.facebook = function(token, tokenSecret, profile, next) {
    var location, model;
    model = this;
    location = typeof profile._json.location !== 'undefined' ? profile._json.location.name : '';
    return model.findOne({
      'facebook.id': profile.id
    }, function(err, doc) {
      var u;
      if (err) {
        return next(err);
      }
      if (doc) {
        if (doc.banned) {
          next(null, false);
        }
        doc.facebook.username = profile.username;
        doc.location = location;
        return doc.save(function(err) {
          if (err) {
            throw err;
          }
          return next(null, doc);
        });
      } else {
        u = new (mongoose.model('user'));
        u.facebook.id = profile.id;
        u.facebook.token_secret = token;
        u.username = u.username = profile.username;
        u.location = location;
        u.provider = profile.provider;
        return u.save(function(err) {
          if (err) {
            throw err;
          }
          return next(null, u);
        });
      }
    });
  };

  module.exports = mongoose.model('user', user);

}).call(this);
